### ISSUE TITLE
getting something error occured-and response as user cancelled payment

### ISSUE THREAD

**Issue by dev-vamsidhar** [abhimortal6/flutter_payu_unofficial#1]

**Comment by abhimortal6** [comment]
This is very common. Do not use test creds get creds from your developer account.

**Comment by dev-vamsidhar** [comment]
Problem is solved thanks for ur package u deserve a like

**Comment by athul-ain** [comment]
Bro is there a way to fix this. We don't have access to payu developer account. We got the test credentials from HDFC bank and only after verifying the working with the test account they will provide actual credential.

**Comment by abhimortal6** [comment]
Test creds doesn't work any more. For test purposes you can create free account and get the creds.

**Comment by ethicdevil** [comment]
I am getting the same error message even after putting live creds. Please help

**Comment by ethicdevil** [comment]
Sorry, it was my bad. I was sending a hash empty string.

There is also a working example in this repo [here](https://github.com/abhimortal6/flutter_payu_unofficial/blob/master/example/lib/main.dart).
